targets = ["//:iterator"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.24.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.24.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.24.0"