targets = ["//:iterator"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.25.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.25.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.25.1"